algoritmo "IMC"
// Autor : Riquelme Reis
// Data : 07/04/2026

var
largura: real
comprimento: real
resultado: real

inicio
// Coleta de dados

    escreva ("Informe a largura de seu terreno: ")
    leia(largura)

    escreva ("Informe comprimento do seu terreno: ")
    leia(comprimento)

// Resultado

   resultado <- largura*comprimento

// Resultado Final
    escreva ("A área de seu terreno é igual á: ", resultado)

fimalgoritmo
